### PR TITLE
Add integration with sidekiq:

### PR DESCRIPTION
**Pull request by rqz13**
* pass headers using sidekiq client and server middleware
* ability to log with tagged request id like it is done for rails server
* ability to log exceptions tagged with request id like it is done for rails server logging

### CODE REVIEW

**Comment by rqz13** [comment]
sample of logs

failed job
```
I, [2018-12-05T11:20:07.836927 #30882]  INFO -- : [eca89eb0-979b-4faf-b1b4-3da390cf207c] [PID: 30882] [TID-gr79zfeoi] [MyWorker JID-f44211c61be9a348388d518f] start
I, [2018-12-05T11:20:07.858623 #30882]  INFO -- : [eca89eb0-979b-4faf-b1b4-3da390cf207c] [PID: 30882] [TID-gr79zfeoi] [MyWorker JID-f44211c61be9a348388d518f] Adding dead MyWorker job f44211c61be9a348388d518f
I, [2018-12-05T11:20:07.859426 #30882]  INFO -- : [eca89eb0-979b-4faf-b1b4-3da390cf207c] [PID: 30882] [TID-gr79zfeoi] [MyWorker JID-f44211c61be9a348388d518f] fail: 0.023 sec
W, [2018-12-05T11:20:07.859549 #30882]  WARN -- : [eca89eb0-979b-4faf-b1b4-3da390cf207c] {"context":"Job raised exception","job":{"class":"MyWorker","args":...... here goes json with sidekiq context"}
W, [2018-12-05T11:20:07.859726 #30882]  WARN -- : [eca89eb0-979b-4faf-b1b4-3da390cf207c] StandardError: message of error
W, [2018-12-05T11:20:07.859752 #30882]  WARN -- : [eca89eb0-979b-4faf-b1b4-3da390cf207c] /here/is/path/for/file:line `method' .... rest backtrace
```

success job
```
I, [2018-12-05T11:12:59.280285 #31581]  INFO -- : [b0c980e6-7afc-4146-9e6e-83e4066c8a11] [PID: 31581] [TID-go26latuh] [MyWorker JID-ad49b01fc6a9cee8ccc769bc] start
I, [2018-12-05T11:13:03.541984 #31581]  INFO -- : [b0c980e6-7afc-4146-9e6e-83e4066c8a11] [PID: 31581] [TID-go26latuh] [MyWorker JID-ad49b01fc6a9cee8ccc769bc] done: 4.262 sec

```

**Comment by wshihadeh** [comment]
IMHO, This change belongs to this gem https://github.com/fidor/request_headers_logger .   The request_headers_middleware is not a sidekiq extension gem nor a logger gem.

**Comment by rqz13** [comment]
@wshihadeh moving loggers to `request_headers_logger` is a good idea, but I would prefer to leave sidekiq's middleware here, because the feature from readme about passing request id in `ActiveResource` or `Faraday` `RequestHeadersMiddleware.store.merge(ActiveResource::Base.headers)` wouldn't work from sidekiq job as it would be missing.
That's why I think it's better to leave it here. Even if it wouldn't be logged here we should proxy request id to next services.

Would it be ok to leave client and server middleware here and add loggers to `request_headers_logger` ?

**Comment by MarcGrimme** [comment]
Hmm. I would kinda second @wshihadeh comments. I don't think in this gem we should have any additional dependency to another 3rd party library that we support (exception is Rails).

I would even go further saying there should be a `request_headers_sidequiq` gem that depends on the `request_headers_middleware`. I didn't check the full code if this makes sense from the code but at least from approach I'd go in that direction.

Saying that I see we have the dep in request_headers_logger to `delayed_job` but definitely this is not a good idea. And I think we discussed it back then and still want to extract it as well. This approach injects unnecessary code and deps (even in the gemspec) that makes the gem harder to understand and use. We should keep the deps to a minimum and extend with modules (other gems).

So isn't it possible to create a `request_headers_sidekiq` and `request_headers_logger_sidekiq` gem that leverages some of the functionality from `request_headers_middleware`?

Generally I like the code and we could really use it but just my 10 cents on the design.

**Comment by rqz13** [comment]
@MarcGrimme take a look here if you interested https://github.com/fidor/request_headers_logger/pull/11
I've migrate from here functionality to `request_headers_logger`

functionality could be moved out from any of this repo, but as a basic idea it would depend on top of `request_headers_middleware`. Btw I don't afraid of development dependencies

**Pull request closed without merging**
